### ISSUE TITLE
get: does not ask for password anymore

### ISSUE THREAD

**Issue by witrin** [iterative/dvc#5677]
# Bug Report

### Description

Using DVC 2.0.7 with a data registry and a HTTP remote protected with Basic authentification does not ask for a password anymore.

### Reproduce

```console
$ docker run --rm -it -v $HOME/.ssh:/root/.ssh python bash
root@5ffcb2b24d66:/# pip install dvc
root@5ffcb2b24d66:/# dvc remote add --global storage https://nexus.example.com
root@5ffcb2b24d66:/# dvc config --global remote.storage.user some.one
root@5ffcb2b24d66:/# dvc get git@gitlab.example.com:data-registry.git foo/bar.jsonl
ERROR: unexpected error - 401 Client Error: Unauthorized for url: https://nexus.example.com/repository/raw/data-registry/c1/f45dfdb4c6dfc11ede789bab73a272   

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```
### Expected

```console
$ docker run --rm -it -v $HOME/.ssh:/root/.ssh python bash
root@8f4a2837be45:/# pip install dvc==1.11.7
root@8f4a2837be45:/# dvc remote add --global storage https://nexus.example.com
root@8f4a2837be45:/# dvc config --global remote.storage.user some.one
root@8f4a2837be45:/# dvc get git@gitlab.example.com:data-registry.git foo/bar.jsonl
Enter a password for host 'nexus.example.com' user 'some.one': 
```

### Environment information

```console
root@5ffcb2b24d66:/# dvc doctor
DVC version: 2.0.7 (pip)
---------------------------------
Platform: Python 3.9.1 on Linux-4.19.121-linuxkit-x86_64-with-glibc2.28
Supports: http, https
```

The data registry is configured as following:

```
[core]
    remote = storage
['remote "storage"']
    url = https://nexus.example.com/repository/raw/data-registry
    method = PUT
    auth = basic
    ask_password = true
```

https://discord.com/channels/485586884165107732/485596304961962003/823953983823544371

**Comment by bachsh** [comment]
is there a workaround for this until it's fixed?

**Comment by efiop** [comment]
@witrin @bachsh Hi guys, are you still running into this issue with the latest dvc (2.3.0)? If so, could you show a verbose log, please? (add -v to the command you are running)

**Comment by guysmoilov** [comment]
@efiop I see that we get the prompt now!
But still seeing issues.

Here is the output trying to get a specific file:
```
$ dvc get -v https://dagshub.com/Guy/private-dvc data/raw/123                                                                                                                                                                                                                                                
2021-06-08 14:34:39,062 DEBUG: Creating external repo https://dagshub.com/Guy/private-dvc@None
2021-06-08 14:34:39,063 DEBUG: erepo: git clone 'https://dagshub.com/Guy/private-dvc' to a temporary dir
2021-06-08 14:34:40,660 DEBUG: Preparing to download data from 'https://dagshub.com/Guy/private-dvc.dvc'
2021-06-08 14:34:40,660 DEBUG: Preparing to collect status from https://dagshub.com/Guy/private-dvc.dvc
2021-06-08 14:34:40,660 DEBUG: Collecting information from local cache...
2021-06-08 14:34:40,661 DEBUG: Collecting information from remote cache...
2021-06-08 14:34:40,661 DEBUG: Matched '0' indexed hashes
2021-06-08 14:34:40,661 DEBUG: Querying 1 hashes via object_exists
2021-06-08 14:34:41,324 DEBUG: Removing '/Users/tolstoyevsky/tmp/dvc-get/.a8QXbMP8bHfBtgJfPcxa54'
2021-06-08 14:34:41,324 ERROR: failed to get 'data/raw/123' from 'https://dagshub.com/Guy/private-dvc' - '401 Unauthorized'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/output.py", line 796, in get_dir_cache
    objects.check(self.odb, self.odb.get(self.hash_info))
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/objects/__init__.py", line 35, in check
    odb.check(obj.hash_info)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 133, in check
    obj.check(self, check_hash=check_hash)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/objects/file.py", line 51, in check
    actual = get_file_hash(
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/objects/stage.py", line 56, in get_file_hash
    raise FileNotFoundError(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tolstoyevsky/tmp/dvc-get/.a8QXbMP8bHfBtgJfPcxa54/0d/764335b9b44f661361ac6fe8a48474.dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/command/get.py", line 37, in _get_file_from_repo
    Repo.get(
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/repo/get.py", line 55, in get
    repo.repo_fs.download(from_info, to_info, jobs=jobs)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/fs/base.py", line 264, in download
    if not _only_file and self.isdir(from_info):
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/fs/repo.py", line 185, in isdir
    meta = dvc_fs.metadata(path)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/fs/dvc.py", line 229, in metadata
    meta.isdir = meta.isdir or self.check_isdir(meta.path_info, meta.outs)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/fs/dvc.py", line 123, in check_isdir
    self._get_granular_hash(path_info, out)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/fs/dvc.py", line 51, in _get_granular_hash
    out.get_dir_cache(remote=remote)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/output.py", line 798, in get_dir_cache
    self.repo.cloud.pull(
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/data_cloud.py", line 84, in pull
    return remote.pull(
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/remote/base.py", line 484, in pull
    ret = self._process(
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/remote/base.py", line 321, in _process
    dir_status, file_status, dir_contents = self._status(
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/remote/base.py", line 173, in _status
    self.hashes_exist(
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/remote/base.py", line 130, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 411, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 362, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/Users/tolstoyevsky/.pyenv/versions/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/Users/tolstoyevsky/.pyenv/versions/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/tolstoyevsky/.pyenv/versions/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/tolstoyevsky/.pyenv/versions/3.8.6/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 353, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/fs/http.py", line 147, in exists
    raise HTTPError(res.status_code, res.reason)
dvc.exceptions.HTTPError: '401 Unauthorized'
------------------------------------------------------------
2021-06-08 14:34:41,338 DEBUG: Analytics is enabled.
2021-06-08 14:34:41,442 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/cg/dlj4z4t96mg59jqh8fz7c4y40000gn/T/tmp_hfvmo71']'
2021-06-08 14:34:41,444 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/cg/dlj4z4t96mg59jqh8fz7c4y40000gn/T/tmp_hfvmo71']'
```

Here is the output trying to get a directory:
```
$ dvc get -v https://dagshub.com/Guy/private-dvc data                                                                                                                                                                                                                                                          
2021-06-08 14:36:07,080 DEBUG: Creating external repo https://dagshub.com/Guy/private-dvc@None
2021-06-08 14:36:07,080 DEBUG: erepo: git clone 'https://dagshub.com/Guy/private-dvc' to a temporary dir
2021-06-08 14:36:08,505 DEBUG: Removing '/Users/tolstoyevsky/tmp/dvc-get/.X9RYcnikhsbut8vRxpXCM7'
2021-06-08 14:36:08,520 ERROR: unexpected error - too many values to unpack (expected 1)
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/command/base.py", line 64, in do_run
    return self.run()
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/command/get.py", line 31, in run
    return self._get_file_from_repo()
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/command/get.py", line 37, in _get_file_from_repo
    Repo.get(
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/repo/get.py", line 55, in get
    repo.repo_fs.download(from_info, to_info, jobs=jobs)
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/fs/base.py", line 264, in download
    if not _only_file and self.isdir(from_info):
  File "/Users/tolstoyevsky/tmp/fds-test/.venv/lib/python3.8/site-packages/dvc/fs/repo.py", line 189, in isdir
    (out,) = meta.outs
ValueError: too many values to unpack (expected 1)
------------------------------------------------------------
2021-06-08 14:36:08,573 DEBUG: Version info for developers:
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.8.6 on macOS-11.3.1-x86_64-i386-64bit
Supports: http, https
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-06-08 14:36:08,575 DEBUG: Analytics is enabled.
2021-06-08 14:36:08,667 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/cg/dlj4z4t96mg59jqh8fz7c4y40000gn/T/tmpb2gfnyfe']'
2021-06-08 14:36:08,669 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/cg/dlj4z4t96mg59jqh8fz7c4y40000gn/T/tmpb2gfnyfe']'
```

Here is a publicly readable copy of the repo, where you can see the managed DVC files I'm trying to `dvc get`:
https://dagshub.com/Guy/public-dvc

**Comment by efiop** [comment]
@guysmoilov FYI: those assertions are now fixed in upstream. Regarding the http error, that might be something related to your server implementation and our httpfs not being compatible with it. I was able to reproduce but unfortunately wasn't able to research deeper yet. If you'd like to take a closer look yourself, that would be really helpful.

**Comment by guysmoilov** [comment]
@efiop Thank you for the update, we'll check it out and update here

**Comment by efiop** [comment]
Closing for now.

**Comment by guysmoilov** [comment]
@efiop Our checks so far say that this isn't fixed, I was waiting until we have a better explanation for why it fails before reporting the results

**Comment by efiop** [comment]
@guysmoilov Are you talking about the http error or the ValueError?

**Comment by guysmoilov** [comment]
HTTP 401

**Comment by efiop** [comment]
@guysmoilov Gotcha. Please feel free to create a new issue when you are ready. This one is a bit overloaded with initial password discussion and ValueError, so better to not add on top. Thanks for the feedback! :pray:
