### ISSUE TITLE
dvc repro --dry --allow-missing: fails on missing data

### ISSUE THREAD

**Issue by Otterpatsch** [iterative/dvc#9818]
## Description

I currently trying to update our ci pipeline. 
Currently we got the following commands (among others).

`dvc pull` to check if everything is pushed
`dvc status` to check if the dvc status is clean. In other words no repro would be run if one would run dvc repro. 

But pulling thats a long time and with the now new --alllow-missing feature i though i can skip that with

```
dvc data status --not-in-remote --json | grep -v not_in_remote
dvc repro --allow-missing --dry
```
the first is working like expected. Fails if data was forgotten to be pushed and succeeds if it was. 
But the later just fails on missing data. 

### Reproduce

Example: Failure/Success on Machine Two and Three should be synced

Machine One:
1. dvc repro -f
2. git add . && git commit -m "repro" && dvc push && git push 
3. dvc repro --allow-missing --dry 
--> doesnt fail, nothing changed (as expected)

Machine Two:
4. dvc data status --not-in-remote --json | grep -v not_in_remote
--> does not fail, everything is pushed and would be pulled
5. dvc repro --allow-missing --dry
--> fails on missing data (unexpected)

Machine Three
4. dvc pull
5. dvc status
--> succeeds 

### Expected

On a machine where i did not `dvc pull` i would expect on a git clean state and a clean `dvc data status --not-in-remote --json | grep -v not_in_remote `state  that `dvc repro --allow-missing --dry` would succed and show me that no stage had to run. 

### Environment information

Linux

**Output of `dvc doctor`:**

```console
$ dvc doctor
09:16:47  DVC version: 3.13.2 (pip)
09:16:47  -------------------------
09:16:47  Platform: Python 3.10.11 on Linux-5.9.0-0.bpo.5-amd64-x86_64-with-glibc2.35
09:16:47  Subprojects:
09:16:47  	dvc_data = 2.12.1
09:16:47  	dvc_objects = 0.24.1
09:16:47  	dvc_render = 0.5.3
09:16:47  	dvc_task = 0.3.0
09:16:47  	scmrepo = 1.1.0
09:16:47  Supports:
09:16:47  	azure (adlfs = 2023.4.0, knack = 0.11.0, azure-identity = 1.13.0),
09:16:47  	gdrive (pydrive2 = 1.16.1),
09:16:47  	gs (gcsfs = 2023.6.0),
09:16:47  	hdfs (fsspec = 2023.6.0, pyarrow = 12.0.1),
09:16:47  	http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
09:16:47  	https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
09:16:47  	oss (ossfs = 2021.8.0),
09:16:47  	s3 (s3fs = 2023.6.0, boto3 = 1.28.17),
09:16:47  	ssh (sshfs = 2023.7.0),
09:16:47  	webdav (webdav4 = 0.9.8),
09:16:47  	webdavs (webdav4 = 0.9.8),
09:16:47  	webhdfs (fsspec = 2023.6.0)
09:16:47  Config:
09:16:47  	Global: /home/runner/.config/dvc
09:16:47  	System: /etc/xdg/dvc
09:16:47  Cache types: <https://error.dvc.org/no-dvc-cache>
09:16:47  Caches: local
09:16:47  Remotes: ssh
09:16:47  Workspace directory: ext4 on /dev/nvme0n1p2
09:16:47  Repo: dvc, git
```

**Comment by Otterpatsch** [comment]
I dont hit any "error" just that notification due to --dry that staged would run. And further notification that some files are missing (dvc tracked). 
But maybe my assumation that `dvc repro --allow-missing --dry` should not fail/report everything is fine and uptodate when i use those flag, iff from some other machine that repro was done and pushed successfully is wrong.
Im very much confused by now

**Comment by dberenbaum** [comment]
It seems like this happens when there is a dependency on data that was tracked via `dvc add`. I can reproduce:

```bash
git clone https://github.com/iterative/example-get-started-experiments.git
cd example-get-started-experiments
dvc repro --allow-missing --dry
```

Verbose output:

```
$ dvc repro -v --allow-missing --dry
2023-08-10 11:15:25,325 DEBUG: v3.14.1.dev2+g04e891cef, CPython 3.11.4 on macOS-13.4.1-arm64-arm-64bit
2023-08-10 11:15:25,325 DEBUG: command: /Users/dave/micromamba/envs/dvc/bin/dvc repro -v --allow-missing --dry
2023-08-10 11:15:25,709 DEBUG: Computed stage: 'data/pool_data.dvc' md5: 'None'
'data/pool_data.dvc' didn't change, skipping
2023-08-10 11:15:25,711 DEBUG: Dependency 'data/pool_data' of stage: 'data_split' changed because it is 'modified'.
2023-08-10 11:15:25,712 DEBUG: stage: 'data_split' changed.
2023-08-10 11:15:25,714 ERROR: failed to reproduce 'data_split': [Errno 2] No such file or directory: '/private/tmp/example-get-started-experiments/data/pool_data'
Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/repo/reproduce.py", line 199, in _reproduce
    ret = repro_fn(stage, upstream=upstream, force=force_stage, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/repo/reproduce.py", line 129, in _reproduce_stage
    ret = stage.reproduce(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/dvc/lib/python3.11/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
           ^^^^^^
  File "/Users/dave/micromamba/envs/dvc/lib/python3.11/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/stage/__init__.py", line 433, in reproduce
    self.run(**kwargs)
  File "/Users/dave/micromamba/envs/dvc/lib/python3.11/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
           ^^^^^^
  File "/Users/dave/micromamba/envs/dvc/lib/python3.11/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/stage/__init__.py", line 599, in run
    self._run_stage(dry, force, allow_missing=allow_missing, **kwargs)
  File "/Users/dave/micromamba/envs/dvc/lib/python3.11/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
           ^^^^^^
  File "/Users/dave/micromamba/envs/dvc/lib/python3.11/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/stage/__init__.py", line 630, in _run_stage
    return run_stage(self, dry, force, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/stage/run.py", line 134, in run_stage
    stage.repo.stage_cache.restore(stage, dry=dry, **kwargs)
  File "/Users/dave/Code/dvc/dvc/stage/cache.py", line 188, in restore
    if not _can_hash(stage):
           ^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/stage/cache.py", line 43, in _can_hash
    if not (dep.protocol == "local" and dep.def_path and dep.get_hash()):
                                                         ^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/output.py", line 553, in get_hash
    _, hash_info = self._get_hash_meta()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/output.py", line 573, in _get_hash_meta
    _, meta, obj = self._build(
                   ^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/output.py", line 566, in _build
    return build(*args, callback=pb.as_callback(), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/dvc/lib/python3.11/site-packages/dvc_data/hashfile/build.py", line 233, in build
    details = fs.info(path)
              ^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc-objects/src/dvc_objects/fs/base.py", line 495, in info
    return self.fs.info(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc-objects/src/dvc_objects/fs/local.py", line 42, in info
    return self.fs.info(path)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/dvc/lib/python3.11/site-packages/fsspec/implementations/local.py", line 87, in info
    out = os.stat(path, follow_symlinks=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/example-get-started-experiments/data/pool_data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/cli/command.py", line 26, in do_run
    return self.run()
           ^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/commands/repro.py", line 13, in run
    stages = self.repo.reproduce(**self._common_kwargs, **self._repro_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 64, in wrapper
    return f(repo, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/repo/scm_context.py", line 151, in run
    return method(repo, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/repo/reproduce.py", line 260, in reproduce
    return _reproduce(steps, graph=graph, on_error=on_error or "fail", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/dvc/dvc/repo/reproduce.py", line 203, in _reproduce
    _raise_error(exc, stage)
  File "/Users/dave/Code/dvc/dvc/repo/reproduce.py", line 167, in _raise_error
    raise ReproductionError(f"failed to reproduce{segment} {names}") from exc
dvc.exceptions.ReproductionError: failed to reproduce 'data_split'

2023-08-10 11:15:25,721 DEBUG: Analytics is disabled.
```

**Comment by dberenbaum** [comment]
Looks like it is failing in my example because `data/pool_data.dvc` is in legacy 2.x format, so the hash info doesn't match the stage dep here:

https://github.com/iterative/dvc/blob/04e891cef929567794ade4e0c2a1bf399666f66e/dvc/stage/__init__.py#L315-L321

The hashes are the same, but debugging shows that the different hash names make it fail:

```
(Pdb) out.hash_info
HashInfo(name='md5-dos2unix', value='14d187e749ee5614e105741c719fa185.dir', obj_name=None)
(Pdb) dep.hash_info
HashInfo(name='md5', value='14d187e749ee5614e105741c719fa185.dir', obj_name=None)
```

@Otterpatsch Does `datasets/benchmark-sets/customer0/2020_11_02.dvc` contain the line `hash: md5` (that line is only present in 3.x files)? Also, could you try to delete the [site cache dir](https://dvc.org/doc/user-guide/project-structure/internal-files#site-cache-dir)?

**Comment by dberenbaum** [comment]
> Looks like it is failing in my example because `data/pool_data.dvc` is in legacy 2.x format, so the hash info doesn't match the stage dep here:

@iterative/dvc Thoughts on how we should treat this? Is it modified or not?

**Comment by daavoo** [comment]
> > Looks like it is failing in my example because `data/pool_data.dvc` is in legacy 2.x format, so the hash info doesn't match the stage dep here:
> 
> @iterative/dvc Thoughts on how we should treat this? Is it modified or not?

IMO, it was an overlook for this scenario

**Comment by dberenbaum** [comment]
@daavoo What does that mean? Do you think we should only compare the hash value and not all hash info?

**Comment by daavoo** [comment]
> @daavoo What does that mean? 

I mean that we should not consider it modified in the example-get-started-experiments scenario.

> Do you think we should only compare the hash value and not all hash info?

I need to take a closer look to see what makes sense

**Comment by Otterpatsch** [comment]
> Does datasets/benchmark-sets/customer0/2020_11_02.dvc contain the line hash: md5 (that line is only present in 3.x files)? Also, could you try to delete the [site cache dir](https://dvc.org/doc/user-guide/project-structure/internal-files#site-cache-dir)?
```
outs:
- md5: f4eb1691cb23a5160a958274b9b9fb41.dir
  size: 55860614
  nfiles: 5491
  path: '2020_11_02'
```
seems it does

With deleting the /var/tmp/dvc (was existing) error persists

**Comment by daavoo** [comment]
So, to give context, the problem appears to be that the `.dvc` file in 2.X format:

https://github.com/iterative/example-get-started-experiments/blob/9dba21cbffb0caad939c63db427eea7f16f3c269/data/pool_data.dvc#L1-L5

That is referenced in a `dvc.lock` in 3.X format as dependency:

https://github.com/iterative/example-get-started-experiments/blob/9dba21cbffb0caad939c63db427eea7f16f3c269/dvc.lock#L6-L10

> Do you think we should only compare the hash value and not all hash info?
> Can't say from the top of my mind. Would need to take a closer look to see what makes sense

Strictly speaking, I guess there could be a collision where we would be miss identifying 2 different things as being the same 🤷

**Comment by efiop** [comment]
> As soon as the contents associated with the .dvc are updated, the file will be updated to 3.X format so the problem would disappear.

@Otterpatsch Is it possible to just force-commit for you to upgrade those hashes? We can't really compare those without computing both, which is undesirable. Seems like just upgrading old lock file should be an easy long-term fix.

**Comment by Otterpatsch** [comment]
How do i upgrade the hashes?

**Comment by dberenbaum** [comment]
@Otterpatsch You can do `dvc commit -f` to upgrade the hashes.

**Comment by dberenbaum** [comment]
@daavoo Are you planning a PR to fix the `dvc commit -f` behavior?

@Otterpatsch Are you still working through this problem? It turns out that `dvc commit -f` won't fix it for you currently. The best workaround for now would be to do `dvc remove datasets/benchmark-sets/customer0/2020_11_02.dvc` followed by `dvc add datasets/benchmark-sets/customer0/2020_11_02.dvc`.

**Comment by daavoo** [comment]
> @daavoo Are you planning a PR to fix the `dvc commit -f` behavior?

yes

**Comment by Otterpatsch** [comment]
> @daavoo Are you planning a PR to fix the `dvc commit -f` behavior?
> 
> @Otterpatsch Are you still working through this problem? It turns out that `dvc commit -f` won't fix it for you currently. The best workaround for now would be to do `dvc remove datasets/benchmark-sets/customer0/2020_11_02.dvc` followed by `dvc add datasets/benchmark-sets/customer0/2020_11_02.dvc`.

alright we will test that. But currently we just rolled back to just jusing dvc pull and dvc status (close to a hour).
 Yeah dvc commit -f did somethings but pipeline was still failing but I wasnt sure if we had some other issues so i tried to find those. 
 As soon as the `dvc commit -f ` fix is implemented should this in theory fix also this issue (when dvc commit -f is run and commited ofc)?

**Comment by dberenbaum** [comment]
Once `datasets/benchmark-sets/customer0/2020_11_02.dvc` is updated to use the 3.0 cache (you should see the field `hash: md5` in that file), then it should fix this issue. If you do `dvc remove datasets/benchmark-sets/customer0/2020_11_02.dvc; dvc add datasets/benchmark-sets/customer0/2020_11_02.dvc`, it should work now.

**Comment by dberenbaum** [comment]
`dvc commit -f` also seems like it would be useful after running `dvc cache migrate` to ensure that all dvc files reference the migrated 3.x cache. See https://discord.com/channels/485586884165107732/563406153334128681/1149449470480760982.

**Comment by Otterpatsch** [comment]
The dvc cache migrate outputs that no file changed in the the cache. Even tho the dvc commit -f did something again but i also rebased the branch which intruce those pipeline changes. 

Sadly the pipeline still fails on the `dvc repro --dry --allow-missing | grep -vz "Running"`. Which a dvc pull it doenst fail

**Comment by dberenbaum** [comment]
> So i do i get rid of the dvc2 .dvc files and replace them with their dvc3 counterpart?

Yes, sorry for the confusion @Otterpatsch. I initially thought `dvc commit -f` would achieve that, but it doesn't do that today. We are looking into changing that, but for now you would need to do this yourself.

**Comment by Otterpatsch** [comment]
> > So i do i get rid of the dvc2 .dvc files and replace them with their dvc3 counterpart?
> 
> Yes, sorry for the confusion @Otterpatsch. I initially thought `dvc commit -f` would achieve that, but it doesn't do that today. We are looking into changing that, but for now you would need to do this yourself.

So i just tried to do that 

`dvc repro --dry --allow-missing` to detect all "bad" dvc files. E.g datasets/benchmark-sets/SomeCompanyName/2020_11_02.dvc
then i run `rm datasets/benchmark-sets/SomeCompanyName/2020_11_02.dvc` to get rid of the bad file and `dvc add datasets/benchmark-sets/SomeCompanyName/2020_11_02` to readd the directory. See below the git diff.
```
 ■■ datasets/benchmark-sets/SomeCompanyName/2020_11_02.dvc                                                               
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -2,4 +2,5 @@ outs:                                                                                               
    2    - md5: f4eb1691cb23a5160a958274b9b9fb41.dir                                                                
    3      size: 55860614                                                                                           
    4      nfiles: 5491                                                                                             
    5  +   hash: md5                                                                                                
    5      path: '2020_11_02'  
```

Now i expected if i run dvc repro --dry --allow-missing to not have an have the output md5: 'None for that one specific file.
But i still do get the same output as earlier
> dvc repro --dry --allow-missing --verbose | grep -P "datasets/benchmark-sets/SomeCompanyName/2020_11_02.dvc"  
2023-09-20 12:34:13,083 DEBUG: Computed stage: 'datasets/benchmark-sets/SomeCompanyName/2020_11_02.dvc' md5: 'None'

**Comment by dberenbaum** [comment]
That debug calls from here:

https://github.com/iterative/dvc/blob/b85608121f21e53298aa3c03dae9bf091174b150/dvc/stage/__init__.py#L466-L473

It will only show a non-empty md5 for an actual stage, not a `.dvc`-tracked data source. The check for `--allow-missing` is separate and comes later, so this is expected.

Is `dvc repro --dry --allow-missing` skipping the stage/working as expected?
